# -*- coding: utf-8 -*-
"""Model_scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139woFFIEN-oW8GancCxoPTbnM-OmOzKS
"""

import numpy as np

"""DEFINING SELF FUNCTION"""

class Node():
  def __init__(self):
      self.features = None #for features selection to spliting
      self.threshold=None #for split value
      self.left=None
      self.right=None
      self.value=None

class DecisionTree():
  def __init__(self,max_depth=10):
    self.max_depth=max_depth
    self.root=None
  def gini(self, y):
    classes = np.unique(y)
    impurity = 1
    for c in classes:
        p = np.sum(y == c) / len(y)
        impurity -= p ** 2
    return impurity
  def information_gain(self, parent, left, right):
        # Calculate information gain of a split
        w_left  = len(left)  / len(parent)
        w_right = len(right) / len(parent)
        return self.gini(parent) - (w_left  * self.gini(left)
                                  + w_right * self.gini(right))
  def best_split(self, X, y):
        # Find best feature and threshold to split on
        best_gain      = -1
        best_feature   = None
        best_threshold = None

        for feature in range(X.shape[1]):
            thresholds = np.unique(X[:, feature])
            for threshold in thresholds:
                left_mask  = X[:, feature] <= threshold
                right_mask = ~left_mask

                if left_mask.sum() == 0 or right_mask.sum() == 0:
                    continue

                gain = self.information_gain(
                    y, y[left_mask], y[right_mask]
                )

                if gain > best_gain:
                    best_gain      = gain
                    best_feature   = feature
                    best_threshold = threshold

        return best_feature, best_threshold

  def build_tree(self, X, y, depth=0):
        # Stop conditions
        if depth >= self.max_depth or len(np.unique(y)) == 1:
            # Leaf node — predict most common class
            value = np.bincount(y).argmax()
            node  = Node()
            node.value = value
            return node

        # Find best split
        feature, threshold = self.best_split(X, y)

        if feature is None:
            node = Node()
            node.value = np.bincount(y).argmax()
            return node

        # Split data
        left_mask  = X[:, feature] <= threshold
        right_mask = ~left_mask

        # Build node
        node           = Node()
        node.feature   = feature
        node.threshold = threshold
        node.left      = self.build_tree(X[left_mask],  y[left_mask],  depth+1)
        node.right     = self.build_tree(X[right_mask], y[right_mask], depth+1)
        return node

  def fit(self, X, y):
        self.root = self.build_tree(X, y)

  def predict_one(self, x, node):
        # Traverse tree for one sample
        if node.value is not None:
            return node.value
        if x[node.feature] <= node.threshold:
            return self.predict_one(x, node.left)
        return self.predict_one(x, node.right)

  def predict(self, X):
        return [self.predict_one(x, self.root) for x in X]

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = DecisionTree(max_depth=10)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
accuracy = np.mean(np.array(predictions) == y_test)
print(f"Accuracy: {accuracy * 100:.2f}%")

