# -*- coding: utf-8 -*-
"""log_reg_scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139woFFIEN-oW8GancCxoPTbnM-OmOzKS
"""

import numpy as np
import pandas as pd

def sigmoid(self,z):
  return 1/(1+np.exp(-z))

print(sigmoid(None, 0))
print(sigmoid(None, 100))
print(sigmoid(None, -100))

class logReg:
    def __init__(self,lr=0.001,epochs=1000):
        self.lr = lr
        self.epochs=epochs
        self.weights = None # Will be initialized in fit
        self.bias = None    # Will be initialized in fit

    def sigmoid(self,z):
        return 1/(1+np.exp(-z))

    def fit(self,X,y):
        n_samples, n_features = X.shape

        # Initialize weights and bias to zeros
        self.weights = np.zeros(n_features)
        self.bias = 0.0 # Use float for bias

        for _ in range(self.epochs):
            # Linear combination
            z = np.dot(X, self.weights) + self.bias
            # Sigmoid activation
            y_pred = self.sigmoid(z)

            # Calculate gradients
            dw = (1/n_samples) * np.dot(X.T, (y_pred - y))
            db = (1/n_samples) * np.sum(y_pred - y)

            # Update weights and bias
            self.weights = self.weights - self.lr * dw
            self.bias = self.bias - self.lr * db

    def predict(self,X):
        z = np.dot(X, self.weights) + self.bias
        y_pred = self.sigmoid(z)
        # Convert probabilities to binary predictions (0 or 1)
        return (y_pred >= 0.5).astype(int)

"""testing

"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data = load_breast_cancer()

X,y=data.data,data.target

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

model = logReg(lr=0.01, epochs=1000)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
accuracy = np.mean(np.array(predictions) == y_test)
print(f"Accuracy: {accuracy * 100:.2f}%")

train_predictions = model.predict(X_train)
train_accuracy = np.mean(np.array(train_predictions) == y_train)
test_accuracy = np.mean(np.array(predictions) == y_test)

print(f"Train Accuracy: {train_accuracy * 100:.2f}%")
print(f"Test  Accuracy: {test_accuracy  * 100:.2f}%")

