# -*- coding: utf-8 -*-
"""ML_notes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139woFFIEN-oW8GancCxoPTbnM-OmOzKS
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
np.random.seed(100)
X=np.random.rand(50,1)*100
Y=3.5*(X)+np.random.randn(50,1)*20
model=LinearRegression()
model.fit(X,Y)
Y_pred=model.predict(X)
from matplotlib import lines
plt.scatter(X,Y)
plt.plot(X,Y_pred,color='red')
plt.grid(True,color='red')
plt.show()

