# -*- coding: utf-8 -*-
"""ML_notes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139woFFIEN-oW8GancCxoPTbnM-OmOzKS
"""

#regresion model
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X, y = load_breast_cancer(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=23)

clf = LogisticRegression(max_iter=10000, random_state=0)
clf.fit(X_train, y_train)

acc = accuracy_score(y_test, clf.predict(X_test)) * 100
print(f"Logistic Regression model accuracy: {acc:.2f}%")
import matplotlib.pyplot as plt
plt.plot(clf.coef_[0])
plt.show()

